# Generated by Django 3.2 on 2023-05-19 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Intercarrier',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre del intercarrier')),
                ('ip', models.CharField(max_length=50, verbose_name='Ip a la que se conecta')),
                ('fecha_conexion', models.DateTimeField(verbose_name='Fecha en la que se realiza la conexion')),
                ('conexiones', models.IntegerField(verbose_name='Numero de conexiones')),
            ],
            options={
                'verbose_name': 'Intercarrier',
                'verbose_name_plural': 'Periodos escolares',
            },
        ),
    ]
